name: vagas_flutter_backend
description: A sample command-line application.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dart_jsonwebtoken: ^2.7.1
  dotenv: ^4.1.0
  mailer: ^6.0.0
  mysql1: ^0.20.0
  password_dart: ^2.0.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^3.0.7
  linux_system_info: ^0.0.7
  shelf_swagger_ui: ^1.0.0+2
  mocktail: ^0.3.0

